options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true
timeout: '1800s'
steps:
  - name: 'python:3.10-slim'
    entrypoint: '/bin/bash'
    args:
    - '-c'
    - |
      pip install -r ./deployment/requirements.txt
      python -c 'print("Hello")'
    id: "install-requirements"
