options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true
substitutions:
  _APPLICATION_NAME: 'recova-dp'
  _REGISTRY: 'europe-west3-docker.pkg.dev'
  _CLIENT_VERSION: 'v0.0.1' # manual
timeout: '1800s'
steps:
  - name: 'python'
    entrypoint: python
    args: ["-c", "import sys; print(f'{sys.version}')"]
    id: 'test-python'
